server:
  port: ${SERVER_PORT:8083}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: monitor-oracle
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${ORACLE_SERVICE}?TNS_ADMIN=${TNS_ADMIN}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

app:
  topic:
    ubicaciones: ${TOPIC_UBICACIONES:ubicaciones_vehiculos}
    horarios: ${TOPIC_HORARIOS:horarios}

appzone:
  tz: America/Santiago
